apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server }}"
      path: "kubernetes"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "/v1/auth/kubernetes"
          role: "student-api-role"   # <-- ADD THIS ROLE NAME
