apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: student-api
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location /api/v1/ {
        proxy_pass http://student-api;
      }
    }
