version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork  

  api1:
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./migrations:/app/migrations
    command: flask run --host=0.0.0.0
    networks:
      - mynetwork  

  api2:
    build:
      context: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "5001:5000"  
    volumes:
      - .:/app
      - ./migrations:/app/migrations
    command: flask run --host=0.0.0.0
    networks:
      - mynetwork  

  nginx:
    image: nginx:latest
    depends_on:
      - api1
      - api2
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork  

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge  