version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    image: student-api:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
