apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault:8200"  # Vault server URL
      path: "secret/db"            # Path where the secret is stored in Vault
