"""empty message

Revision ID: f3a7d3c418ce
Revises: 
Create Date: 2025-03-06 08:41:49.541075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a7d3c418ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
