version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
