version: '3.8'

services:
  api:
    image: student-api:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
